language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database mramirol_test;' -U postgres
rvm:
 - 2.2.3
services:
 - postgresql
addons:
 code_climate:
  repo_token: 4d081c0f9fe7aad2c64a421a91550a4b0763dcb41b803f1c639d42eb6fc9c359
