default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mramirol_development

test:
  <<: *default
  database: mramirol_test

production:
  <<: *default
  host: mramirol.cza0fl5qataj.ap-southeast-1.rds.amazonaws.com
  database: amirol_production
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
